version: '3'
services:
  back-end:
    build:
      context: ./back-end
    image: softy-pinko-back-end:task4
    ports:
      - "9999:4567"

  front-end:
    build:
      context: ./front-end
    image: softy-pinko-front-end:task4
    ports:
      - "9999:9000"
    depends_on:
      - back-end
