version: '3'
services:
  softy-pinko-front-end:
    build:
      context: ./front-end
    image: softy-pinko-front-end:task5
    ports:
      - "9999:9000"
    depends_on:
      - softy-pinko-back-end

  softy-pinko-back-end:
    build:
      context: ./back-end
    image: softy-pinko-back-end:task5
    ports:
      - "9999:4567"
    deploy:
      mode: replicated
      replicas: 2

  softy-pinko-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - softy-pinko-front-end
      - softy-pinko-back-end
